Added phpmd support

diff --git a/phpcs-pre-commit/pre-commit b/phpcs-pre-commit/pre-commit
--- a/phpcs-pre-commit/pre-commit
+++ b/phpcs-pre-commit/pre-commit
@@ -1,10 +1,6 @@
 #!/bin/bash
-# PHP CodeSniffer pre-commit hook for git
-#
-# @author Soenke Ruempler <soenke@ruempler.eu>
-# @author Sebastian Kaspari <s.kaspari@googlemail.com>
-#
-# see the README
+# Branched and added PHPMD support 
+ 
 
 PHPCS_BIN=/usr/bin/phpcs
 PHPCS_CODING_STANDARD=PEAR
@@ -12,7 +8,7 @@ PHPCS_IGNORE=
 TMP_STAGING=".tmp_staging"
 
 # parse config
-CONFIG_FILE=$(dirname $0)/config
+CONFIG_FILE=$(dirname $0)/php-chconfig
 if [ -e $CONFIG_FILE ]; then
     . $CONFIG_FILE
 fi
@@ -22,6 +18,13 @@ if [ ! -x $PHPCS_BIN ]; then
     echo "PHP CodeSniffer bin not found or executable -> $PHPCS_BIN"
     exit 1
 fi
+
+# simple check if mess detector is set up correctly
+if [ ! -x $PHPMD_BIN ]; then
+    echo "PHP MessDetector bin not found or executable -> $PHPMD_BIN"
+    exit 1
+fi
+
 
 # stolen from template file
 if git rev-parse --verify HEAD
@@ -82,6 +85,7 @@ else
     IGNORE_WARNINGS=""
 fi
 
+
 # Copy contents of staged version of files to temporary staging area
 # because we only want the staged version that will be commited and not
 # the version in the working directory
@@ -100,11 +104,25 @@ done
 OUTPUT=$($PHPCS_BIN -s $IGNORE_WARNINGS  --standard=$PHPCS_CODING_STANDARD $ENCODING $IGNORE $STAGED_FILES)
 RETVAL=$?
 
-# delete temporary copy of staging area
-rm -rf $TMP_STAGING
-
 if [ $RETVAL -ne 0 ]; then
     echo "$OUTPUT" | less
 fi
 
 exit $RETVAL
+
+while read line ; do
+  OUTPUT=$($PHPMD_BIN $line $PHPMD_FORMAT $PHPMD_RULESET)
+  RETVAL=$?
+
+  if [ $RETVAL -ne 0 ]; then
+      echo "$OUTPUT" | less
+  fi
+
+  exit $RETVAL
+
+done < $STAGED_FILES
+
+
+# delete temporary copy of staging area
+rm -rf $TMP_STAGING
+
